theme: minima
title: "storytelling through data: a portfolio."
author: "lorraine wheat"
descrption: "exploring modern-day trends through data with an eye geared towards women, millennials, and gen z."
